apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-a-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a-deployment
  namespace: api
  labels:
    app.kubernetes.io/name: microservice-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-a
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice-a
    spec:
      automountServiceAccountToken: false
      serviceAccount: microservice-a-sa
      securityContext:
        runAsUser: 10001
        runAsGroup: 3000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - microservice-a
            topologyKey: kubernetes.io/hostname
      containers:
      - name: microservice-a
        image: YOUR_ACR.azurecr.io/live/a0005/chain-api:5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          protocol: TCP
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: DEEPTH
          value: "1"
        - name: SELF_HOSTS_DEPENDENCIES
          value: http://localhost
        - name: EXTERNAL_DEPENDENCIES
          value: https://packages.microsoft.com
        - name: ASPNETCORE_URLS
          value: http://*:8080
      nodeSelector:
        pci-scope: out-of-scope
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: microservice-a-pdb
  namespace: api
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-a
---
kind: Service
apiVersion: v1
metadata:
  name: microservice-a-service
  namespace: api
spec:
  selector:
    app.kubernetes.io/name: microservice-a
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web