apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osm-system
resources:
- namespace.yaml
#- resource-quota.yaml
#- limit-range.yaml
#- rbac.yaml
- osm/osm-crds.yaml
- osm/osm.yaml
secretGenerator:
  - name: osm-acr-instance
    type: Opaque
    literals:
      - name=REPLACE_ME_WITH_YOUR_ACRNAME
