apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-c-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-c
  labels:
    app.kubernetes.io/name: microservice-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-c
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice-c
    spec:
      automountServiceAccountToken: false
      serviceAccount: microservice-c-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - microservice-c
            topologyKey: kubernetes.io/hostname
      containers:
      - name: microservice-c
        image: YOUR_ACR.azurecr.io/live/a0005/chain-api:5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          protocol: TCP
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10001
          runAsGroup: 3000
          capabilities:
            drop:
              - all
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: DEEPTH
          value: "1"
        - name: SELF_HOSTS_DEPENDENCIES
          value: http://microservice-web-service.a0005-is,http://microservice-a-service.a0005-oos,http://microservice-b-service.a0005-oos
        - name: EXTERNAL_DEPENDENCIES
          value: https://packages.microsoft.com,https://example.org
        - name: ASPNETCORE_URLS
          value: http://*:8080
      nodeSelector:
        pci-scope: out-of-scope
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: microservice-c-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-c
---
kind: Service
apiVersion: v1
metadata:
  name: microservice-c-service
spec:
  selector:
    app.kubernetes.io/name: microservice-c
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web